// TEST USERS TABLE

GET http://localhost:8080/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MzJlM2Q5OS0yMDI4LTExZWYtOWQ3NC1jMDE4MDMzZDM1ODAiLCJ1c2VybmFtZSI6InVuZGVmaW5lZCIsImVtYWlsIjoic2ViZXBhOTEwM0Bjcm9kaXR5LmNvbSIsImlhdCI6MTcxNzI1NTEzMiwiZXhwIjoxNzE3MjU1MTQ3fQ.vYP_W3kS6wJfdW_BfcTu4Fzv1wlK7Z5yd04dWZM-kB4

###
POST http://localhost:8080/api/v1/register
Content-Type: application/json

{
    "fullname":"Silvi Putri",
    "username":"Silvi Putri",
    "phoneNumber":"+6281234567892",
    "email":"sebepa9103@crodity.com",
    "password":"silvi123",
    "confPassword":"silvi123"
}

###
POST http://localhost:8080/api/v1/register
Content-Type: application/json

{
    "fullname":"John Cena",
    "username":"johncena",
    "phoneNumber":"+628987654321",
    "email":"kenex19195@avastu.com",
    "password":"johncena123",
    "confPassword":"johncena123"
}

###
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
    "email" : "sebepa9103@crodity.com",
    "password" : "silvi123"
}

###
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
    "email" : "kenex19195@avastu.com",
    "password" : "johncena123"
}

###
POST http://localhost:8080/api/v1/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1MzJlM2Q5OS0yMDI4LTExZWYtOWQ3NC1jMDE4MDMzZDM1ODAiLCJ1c2VybmFtZSI6InVuZGVmaW5lZCIsImVtYWlsIjoic2ViZXBhOTEwM0Bjcm9kaXR5LmNvbSIsImlhdCI6MTcxNzI1NTEwMywiZXhwIjoxNzE3MjU1MTE4fQ.t2w-mZRpOcLi2Iq5O1D-XrQ4Cu3PsLfv-TCS-MXzR5M

Content-Type: application/json
{
    "username":"Silva Putra",
    "avatar":null
}

###
POST http://localhost:8080/api/v1/users/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlYTcyY2Y1Yi0xZmYyLTExZWYtOWQ3NC1jMDE4MDMzZDM1ODAiLCJ1c2VybmFtZSI6InVuZGVmaW5lZCIsImVtYWlsIjoibmFib2hpNTYxOUBhY3V4aS5jb20iLCJpYXQiOjE3MTcyNTI4NDcsImV4cCI6MTcxNzI1Mjg2Mn0.a8dqNZpGtVDefp8TkzL105xU-1LmZFtGGj9wSD_o4V0

Content-Type: application/json

{
    "username":"Johnny Cage",
    "avatar":null
}

###
GET http://localhost:8080/api/v1/token

###
DELETE http://localhost:8080/api/v1/logout


// TEST TRANSACTION TABLE
###
GET http://localhost:8080/api/v1/transaction
Content-Type: application/json

{
    "userId" : "2462aba8-1e31-11ef-b5ba-c018033d3580"
}

###
POST http://localhost:8080/api/v1/transaction
Content-Type: application/json

{
    "userId" : "2462aba8-1e31-11ef-b5ba-c018033d3580",
    "type" : "expenses",
    "amount": 1500000.00,
    "detail":"Makan Kentang"
}


