// TEST USERS TABLE

GET http://localhost:8080/api/v1/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmNGEyYWE1Ni0xZmVmLTExZWYtOWQ3NC1jMDE4MDMzZDM1ODAiLCJ1c2VybmFtZSI6IlNpbHZpIFB1dHJpIiwiZW1haWwiOiJuZXlheTUyNDI4QGFjdXhpLmNvbSIsImlhdCI6MTcxNzIzMDU3MSwiZXhwIjoxNzE3MjMwNTkxfQ.6NB_iZwWwpdZTjmNM--lwI_V-plU6uEW1lG0S_wgMZ8

###
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
    "fullname":"Silvi Putri",
    "username":"Silvi Putri",
    "phoneNumber":"+6281234567892",
    "email":"nabohi5619@acuxi.com",
    "password":"silvi123",
    "confPassword":"silvi123"
}

###
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
    "email" : "nabohi5619@acuxi.com",
    "password" : "silvi123"
}

###
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
    "id": "b77018d7-1e58-11ef-b5ba-c018033d3580",
    "userName" : "silvi123"
}

###
GET http://localhost:8080/api/v1/token

###
DELETE http://localhost:8080/api/v1/logout


// TEST TRANSACTION TABLE
###
GET http://localhost:8080/api/v1/transaction
Content-Type: application/json

{
    "userId" : "2462aba8-1e31-11ef-b5ba-c018033d3580"
}

###
POST http://localhost:8080/api/v1/transaction
Content-Type: application/json

{
    "userId" : "2462aba8-1e31-11ef-b5ba-c018033d3580",
    "type" : "expenses",
    "amount": 1500000.00,
    "detail":"Makan Kentang"
}


